[functions]
  # Specifies `esbuild` for functions bundling
  node_bundler = "esbuild"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"